### PR TITLE
tweak/2021-jul/newsletter-signup Lead with the Benefits rather than Yet Another Newsletter

### PR DESCRIPTION
**Pull request by winterstein**

### CODE REVIEW

**Comment by winterstein** [comment]
@wongws11 Ready to merge?

**Comment by wongws11** [comment]
Because it turns out our design does want to have a register button inside of the How It Works Card svg file. I roll the button back, which causes the error in Safari. This error is quite weird because my Safari gives me a 'The operation is not supported' error for the `getSVGDocument` feature. While https://caniuse.com/mdn-api_htmlembedelement_getsvgdocument does indicate it should be supported in Safari. 

For now I moved the CTA button out of the desktop version of SVG file in order to avoid the Safari bug. But this is not a ideal layout. We have two options after this: 1. figure out why `getSVGDocument` is not working in Safari or use another method; or 2. redraw the SVG a bit, or make it into two separated SVG in order to have a good layout without making a button inside of a SVG.

**Comment by winterstein** [comment]
Hello Wing


On Mon, 5 Jul 2021 at 15:10, wongws11 ***@***.***> wrote:

> Because it turns out our design does want to have a register button inside
> of the How It Works Card svg file. I roll the button back, which causes the
> error in Safari. This error is quite weird because my Safari gives me a
> 'The operation is not supported' error for the getSVGDocument feature.
> While https://caniuse.com/mdn-api_htmlembedelement_getsvgdocument does
> indicate it should be supported in Safari.
>
> For now I moved the CTA button out of the desktop version of SVG file in
> order to avoid the Safari bug.
>

That sounds like exactly the right action for now. Thanks.


> But this is not a ideal layout. We have two options after this: 1. figure
> out why getSVGDocument is not working in Safari or use another method; or
> 2. redraw the SVG a bit, or make it into two separated SVG in order to have
> a good layout without making a button inside of a SVG.
>

Fighting browsers is painful. Splitting the svg is probably the best way.
It also feels "right", in that html is the more natural place for a normal
button.

Suggested time frame: Sometime in July.

 - Dan

**Comment by wongws11** [comment]
In fact the current [testmy.good-loop.com](testmy.good-loop.com) is using the spilt svg I made really quickly. The only thing left to do with it is to clean up the codes of the two svg to make them less fat.

**Pull request merged**
