### PR TITLE
Feature/set per charity campaign donations

### PR DESCRIPTION
**Pull request by winterstein**
@dodo721 

Hello Ben

This PR (+ edits in adserver and wwappbase.js code) adds a field for setting the per-charity donations.
I refactored and tidied up the donation calculation code a bit (it was a mess from a couple of former editors - sorry for that).
This code is *not* tested! I expect some bugs will crawl out.

 - Dan

### CODE REVIEW

**Comment by dodo721** [comment]
Code looks good to me from reading - however my local copy is failing to load, with these errors:
image
Will do more debugging soon but getting lunch first!

**Comment by winterstein** [comment]
Hello Ben

OK - that's fixed. But there are some other errors

 -- Impact Hub isn't showing any charity cards.
http://localmy.good-loop.com/#campaign/?gl.vert=CeuNVbtW

-- and there's a £ NaN here:
http://localmy.good-loop.com/#campaign/?gl.vert=ma9LU5chyU

Could you take a look?

Thanks,
 - Dan

**Comment by dodo721** [comment]
Hi Dan, fixed the issue - a couple typos and bad use of Object.entries were responsible.
Looks to be working now!

**Comment by winterstein** [comment]
Let's merge :) I'll push the button now

**Pull request merged**
