### PR TITLE
Big cleanup of AdvertsCatalogue

### PR DESCRIPTION
**Pull request by roscoemcinerney**
NB this isn't fixing show-stopping bugs, so don't worry about scrambling to get it fully tested for release. Just getting my local git cleaned up.

A little more complicated in some ways (now probes its container for available space & sets some utility classes to fix aspect ratio), overall should be simpler & more flexible.

Should now show at the right size in most contexts - places to test, off the top of my head:
- Impact Overview: the small preview card & the full-window modal
- Impact Stories: the ad preview in the phone frame
- Legacy campaign pages

### CODE REVIEW

**Comment by athomson0** [comment]
On stage, I'm unable to play this Purina advert:   

image


https://stagemy.good-loop.com/impact/stories/brand/VAcnHLcz?open=false  

---  

Also, the page breaks and has many errors when logging in with a non-GL account and attempting to view the above link. Is this the expected behavior for now?

**Comment by athomson0** [comment]
https://stagemy.good-loop.com/campaign/toms_ella_2019?server=production  

The controls no longer work on these ads. They disappear as soon as you hover over them. Clicking the video to try and pause it switches to a different advert, but the current one will remain playing in the background.

**Comment by athomson0** [comment]
https://stagemy.good-loop.com/campaign/matt_nike_3729?server=production

image

There are two carousel controls here. Two under the video, one overlaid on top of the video. The ones below the video don't work - clicking them won't switch between adverts.

**Comment by athomson0** [comment]
https://stagemy.good-loop.com/impact/stories/brand/q44DhUNr  

The adunit is clipping under the iPhone here.  

image

**Comment by roscoemcinerney** [comment]
Stage is definitely not running that new branch - but the branch code also
has some (different) glitches in those contexts. I'll update shortly.

**Comment by roscoemcinerney** [comment]
OK, there's a matching branch in wwappbase.js which tweaks GoodLoopUnit in
a similar way, and additional commits in this branch to fix some logic
issues which were breaking the sizing of ads while paging through the
carousel, and set the display size of the ads catalogue on the legacy
campaign page.

Paging controls should make a lot more sense now:
- If there's only one advert, that's all that gets shown. No selector list,
no prev/next button.
- If there are multiple adverts, you'll see prev/next buttons next to the
main ad display, and either a row of smaller previews (larger screens) or a
row of indicator buttons (smaller screens) below it.
- If there are more than 4 adverts, on larger screens you'll also see
prev/next PAGE buttons next to the live previews, and a row of indicator
buttons for selecting pages directly.

**Review by athomson0 — APPROVED** [review]

**Pull request merged**
